apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: management-console
      port: 15672
    - name: queue-port
      port: 5672
    - name: cluster-port
      port: 4369
    - name: dist-port
      port: 25672
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
        ports:
          - name: queue-port
            containerPort: 5672
          - name: management-port
            containerPort: 15672
          - name: cluster-port
            containerPort: 4369
          - name: dist-port
            containerPort: 25672
        env: 
          - name: RABBITMQ_DEFAULT_USER
            value: root
          - name: RABBITMQ_DEFAULT_PASS
            value: "root"
          - name: RABBITMQ_LOG_LEVEL
            value: "info"
          - name: RABBITMQ_ERLANG_COOKIE
            value: "secret"
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          - name: RABBITMQ_DEFAULT_VHOST
            value: "/"
        