apiVersion: v1
kind: Service
metadata: 
  name: elasticsearch
  labels:
    app: elasticsearch
    visualize: "true"
spec: 
  ports:
    # the port that this service should serve on
    - port: 9200
      name: es-transport
    - port: 9300
      name: es-cluster
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: elasticsearch