apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: place
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /api/v1/place
    route:
    - destination:
        host: place
